
name: Deploy HTML with Secret

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create config.js with secret
        run: |
          echo "const MY_SECRET = \"${{ secrets.SUPABASE_ANON_KEY }}\";" > config.js
